import type {
  Alert,
  AuditEntry,
  Contribution,
  DonationNeed,
  FieldUpdate,
  Hospital,
  Incident,
  InfrastructureAsset,
  PlatformUser,
  ResourceItem,
  ResponseTeam,
  RiskZone,
  RoadSegment,
  Shelter,
  VolunteerTask,
  WeatherSnapshot,
} from "./types";

/**
 * DEMO DATASET — realistic Andhra Pradesh disaster-response sample data.
 * Clearly marked as demo in the UI. Replace with API reads in `src/lib/api`.
 */

export const AP_CENTER = { lat: 16.35, lng: 80.85 };

export const DISTRICTS = [
  "Konaseema",
  "Krishna",
  "NTR",
  "Guntur",
  "Bapatla",
  "West Godavari",
  "Eluru",
  "Kakinada",
  "Nellore",
  "Prakasam",
];

const now = Date.UTC(2026, 7, 19, 9, 0, 0);
const ago = (mins: number) => new Date(now - mins * 60_000).toISOString();

export const incidents: Incident[] = [
  {
    id: "INC-24817",
    title: "Families stranded on rooftops, Ainavilli mandal",
    description:
      "Godavari backwater flooding has cut off Chinthalapalem hamlet. Around 42 residents including infants are on rooftops. Water level rising steadily since midnight. Boat access required urgently.",
    category: "RESCUE_REQUEST",
    severity: "CRITICAL",
    status: "VERIFIED",
    district: "Konaseema",
    mandal: "Ainavilli",
    location: { lat: 16.5561, lng: 81.9012 },
    peopleAffected: 42,
    reportedBy: "Sailaja Kondapalli",
    reporterRole: "CITIZEN",
    reporterReportCount: 7,
    hasEvidence: true,
    gpsAccuracyMeters: 6,
    reportedAt: ago(96),
    updatedAt: ago(21),
    verifiedBy: "Officer R. Vamsi Krishna",
    roadAccessible: false,
    timeline: [
      { at: ago(96), status: "SUBMITTED", note: "Citizen report received with 3 photos.", actor: "Sailaja Kondapalli" },
      { at: ago(88), status: "UNDER_REVIEW", note: "Cross-checked against 2 nearby reports.", actor: "Control Room" },
      { at: ago(74), status: "VERIFIED", note: "Verified by field officer on VHF confirmation.", actor: "Officer R. Vamsi Krishna" },
    ],
  },
  {
    id: "INC-24822",
    title: "Cardiac patient needs evacuation, Mummidivaram",
    description:
      "68-year-old cardiac patient at flooded residence. Requires ambulance and medical escort. Approach road submerged up to knee depth.",
    category: "MEDICAL_EMERGENCY",
    severity: "CRITICAL",
    status: "RESPONSE_ASSIGNED",
    district: "Konaseema",
    mandal: "Mummidivaram",
    location: { lat: 16.6407, lng: 82.0894 },
    peopleAffected: 3,
    reportedBy: "Dr. Prasad Yalamanchili",
    reporterRole: "VOLUNTEER",
    reporterReportCount: 24,
    hasEvidence: true,
    gpsAccuracyMeters: 4,
    reportedAt: ago(58),
    updatedAt: ago(12),
    verifiedBy: "Officer K. Anitha",
    assignedTeamId: "TEAM-AMB-A7",
    roadAccessible: true,
    timeline: [
      { at: ago(58), status: "SUBMITTED", note: "Volunteer report with patient vitals.", actor: "Dr. Prasad Yalamanchili" },
      { at: ago(46), status: "VERIFIED", note: "Verified against PHC register.", actor: "Officer K. Anitha" },
      { at: ago(30), status: "RESPONSE_ASSIGNED", note: "Ambulance A7 dispatched, ETA 8 minutes.", actor: "Control Room" },
    ],
  },
  {
    id: "INC-24830",
    title: "Bridge approach slab washed out — Kolleru link road",
    description:
      "Approach slab on the Kolleru link bridge has been washed out over a 6 metre stretch. Two-wheelers still attempting crossing. Barricading requested.",
    category: "BRIDGE_DAMAGE",
    severity: "HIGH",
    status: "IN_PROGRESS",
    district: "Eluru",
    mandal: "Kaikaluru",
    location: { lat: 16.5581, lng: 81.2094 },
    peopleAffected: 0,
    reportedBy: "Constable M. Ravi",
    reporterRole: "FIELD_OFFICER",
    reporterReportCount: 41,
    hasEvidence: true,
    gpsAccuracyMeters: 9,
    reportedAt: ago(210),
    updatedAt: ago(35),
    verifiedBy: "Officer R. Vamsi Krishna",
    assignedTeamId: "TEAM-ENG-3",
    roadAccessible: true,
    timeline: [
      { at: ago(210), status: "SUBMITTED", note: "Reported during patrol.", actor: "Constable M. Ravi" },
      { at: ago(190), status: "VERIFIED", note: "R&B engineer confirmed scour damage.", actor: "Officer R. Vamsi Krishna" },
      { at: ago(120), status: "IN_PROGRESS", note: "Engineering team 3 barricading both approaches.", actor: "Control Room" },
    ],
  },
  {
    id: "INC-24834",
    title: "Drinking water contamination reported at relief camp",
    description:
      "Residents at Kaikaluru relief camp report muddy water from the borewell. Around 180 people dependent on this source.",
    category: "WATER_SHORTAGE",
    severity: "HIGH",
    status: "UNDER_REVIEW",
    district: "Eluru",
    mandal: "Kaikaluru",
    location: { lat: 16.5502, lng: 81.2201 },
    peopleAffected: 180,
    reportedBy: "Volunteer Team Sankalp",
    reporterRole: "VOLUNTEER",
    reporterReportCount: 12,
    hasEvidence: false,
    gpsAccuracyMeters: 18,
    reportedAt: ago(64),
    updatedAt: ago(64),
    roadAccessible: true,
    timeline: [
      { at: ago(64), status: "SUBMITTED", note: "Awaiting officer verification.", actor: "Volunteer Team Sankalp" },
    ],
  },
  {
    id: "INC-24839",
    title: "Water entering homes at Penumudi ferry colony",
    description:
      "Krishna river spill has entered around 30 houses in the ferry colony. Residents shifting belongings to first floors.",
    category: "FLOOD",
    severity: "HIGH",
    status: "VERIFIED",
    district: "Guntur",
    mandal: "Kollipara",
    location: { lat: 16.3389, lng: 80.7645 },
    peopleAffected: 120,
    reportedBy: "Gopala Rao B.",
    reporterRole: "CITIZEN",
    reporterReportCount: 2,
    hasEvidence: true,
    gpsAccuracyMeters: 11,
    reportedAt: ago(140),
    updatedAt: ago(52),
    verifiedBy: "Officer K. Anitha",
    roadAccessible: true,
    timeline: [
      { at: ago(140), status: "SUBMITTED", note: "Report with 2 photos.", actor: "Gopala Rao B." },
      { at: ago(120), status: "UNDER_REVIEW", note: "Duplicate check against INC-24841.", actor: "Control Room" },
      { at: ago(96), status: "VERIFIED", note: "Field confirmation by ward secretary.", actor: "Officer K. Anitha" },
    ],
  },
  {
    id: "INC-24841",
    title: "Flooding near Penumudi ferry point",
    description: "Water has come into the street near the ferry point. Around 25-30 houses affected.",
    category: "FLOOD",
    severity: "MEDIUM",
    status: "SUBMITTED",
    district: "Guntur",
    mandal: "Kollipara",
    location: { lat: 16.3401, lng: 80.7669 },
    peopleAffected: 100,
    reportedBy: "Anonymous citizen",
    reporterRole: "CITIZEN",
    reporterReportCount: 1,
    hasEvidence: false,
    gpsAccuracyMeters: 42,
    reportedAt: ago(118),
    updatedAt: ago(118),
    roadAccessible: true,
    timeline: [{ at: ago(118), status: "SUBMITTED", note: "Awaiting triage.", actor: "Anonymous citizen" }],
  },
  {
    id: "INC-24845",
    title: "Ration stock exhausted at Repalle camp",
    description: "Relief camp at Repalle has less than one day of dry ration for 260 people.",
    category: "FOOD_SHORTAGE",
    severity: "MEDIUM",
    status: "RESPONSE_ASSIGNED",
    district: "Bapatla",
    mandal: "Repalle",
    location: { lat: 16.0189, lng: 80.8291 },
    peopleAffected: 260,
    reportedBy: "Camp Warden S. Latha",
    reporterRole: "FIELD_OFFICER",
    reporterReportCount: 33,
    hasEvidence: true,
    gpsAccuracyMeters: 7,
    reportedAt: ago(300),
    updatedAt: ago(88),
    verifiedBy: "Officer K. Anitha",
    assignedTeamId: "TEAM-REL-9",
    roadAccessible: true,
    timeline: [
      { at: ago(300), status: "SUBMITTED", note: "Camp register attached.", actor: "Camp Warden S. Latha" },
      { at: ago(280), status: "VERIFIED", note: "Stock register verified.", actor: "Officer K. Anitha" },
      { at: ago(240), status: "RESPONSE_ASSIGNED", note: "Relief convoy 9 loading from Guntur godown.", actor: "Control Room" },
    ],
  },
  {
    id: "INC-24850",
    title: "Distribution transformer submerged, Nagayalanka",
    description: "DTR at ward 4 is partially submerged. Power shut down as precaution. 400+ households without supply.",
    category: "INFRASTRUCTURE_DAMAGE",
    severity: "MEDIUM",
    status: "IN_PROGRESS",
    district: "Krishna",
    mandal: "Nagayalanka",
    location: { lat: 15.9541, lng: 80.9209 },
    peopleAffected: 1600,
    reportedBy: "APEPDCL Lineman",
    reporterRole: "FIELD_OFFICER",
    reporterReportCount: 18,
    hasEvidence: true,
    gpsAccuracyMeters: 5,
    reportedAt: ago(400),
    updatedAt: ago(110),
    verifiedBy: "Officer R. Vamsi Krishna",
    assignedTeamId: "TEAM-ENG-3",
    roadAccessible: true,
    timeline: [
      { at: ago(400), status: "SUBMITTED", note: "Reported by discom lineman.", actor: "APEPDCL Lineman" },
      { at: ago(380), status: "VERIFIED", note: "Confirmed by section officer.", actor: "Officer R. Vamsi Krishna" },
      { at: ago(300), status: "IN_PROGRESS", note: "Restoration after water recedes.", actor: "Control Room" },
    ],
  },
  {
    id: "INC-24855",
    title: "Approach road cut off at Machilipatnam outer ring",
    description: "Road washed out for 20 metres; heavy vehicles diverted via NH-216.",
    category: "ROAD_DAMAGE",
    severity: "LOW",
    status: "RESOLVED",
    district: "Krishna",
    mandal: "Machilipatnam",
    location: { lat: 16.1875, lng: 81.1389 },
    peopleAffected: 0,
    reportedBy: "R&B Field Unit",
    reporterRole: "FIELD_OFFICER",
    reporterReportCount: 57,
    hasEvidence: true,
    gpsAccuracyMeters: 8,
    reportedAt: ago(1400),
    updatedAt: ago(420),
    verifiedBy: "Officer K. Anitha",
    roadAccessible: true,
    timeline: [
      { at: ago(1400), status: "SUBMITTED", note: "Reported by R&B unit.", actor: "R&B Field Unit" },
      { at: ago(1300), status: "VERIFIED", note: "Site inspected.", actor: "Officer K. Anitha" },
      { at: ago(420), status: "RESOLVED", note: "Temporary gravel diversion opened.", actor: "Control Room" },
    ],
  },
  {
    id: "INC-24861",
    title: "Shelter roof leaking at Avanigadda school camp",
    description: "Two classrooms unusable due to leaking roof. 60 evacuees relocated to corridor.",
    category: "SHELTER_ISSUE",
    severity: "MEDIUM",
    status: "VERIFIED",
    district: "Krishna",
    mandal: "Avanigadda",
    location: { lat: 16.0203, lng: 80.9192 },
    peopleAffected: 60,
    reportedBy: "Volunteer Harika P.",
    reporterRole: "VOLUNTEER",
    reporterReportCount: 9,
    hasEvidence: true,
    gpsAccuracyMeters: 12,
    reportedAt: ago(180),
    updatedAt: ago(90),
    verifiedBy: "Officer K. Anitha",
    roadAccessible: true,
    timeline: [
      { at: ago(180), status: "SUBMITTED", note: "Photos of leak submitted.", actor: "Volunteer Harika P." },
      { at: ago(90), status: "VERIFIED", note: "Verified by camp officer.", actor: "Officer K. Anitha" },
    ],
  },
];

export const shelters: Shelter[] = [
  {
    id: "SHL-04",
    name: "ZP High School Relief Centre, Amalapuram",
    district: "Konaseema",
    location: { lat: 16.5786, lng: 82.0061 },
    capacity: 420,
    occupancy: 293,
    status: "OPEN",
    facilities: ["Kitchen", "Medical desk", "Women's block", "Generator"],
    contact: "0884-223 4411",
    updatedAt: ago(25),
  },
  {
    id: "SHL-11",
    name: "Municipal Community Hall, Kaikaluru",
    district: "Eluru",
    location: { lat: 16.5525, lng: 81.2154 },
    capacity: 260,
    occupancy: 244,
    status: "NEAR_FULL",
    facilities: ["Kitchen", "Drinking water", "Toilets"],
    contact: "08677-233 190",
    updatedAt: ago(40),
  },
  {
    id: "SHL-18",
    name: "Government Junior College, Repalle",
    district: "Bapatla",
    location: { lat: 16.0176, lng: 80.8302 },
    capacity: 380,
    occupancy: 260,
    status: "OPEN",
    facilities: ["Kitchen", "Medical desk", "Child care"],
    contact: "08648-222 105",
    updatedAt: ago(70),
  },
  {
    id: "SHL-22",
    name: "Cyclone Shelter, Nagayalanka",
    district: "Krishna",
    location: { lat: 15.9498, lng: 80.9251 },
    capacity: 500,
    occupancy: 500,
    status: "FULL",
    facilities: ["Kitchen", "Generator", "Livestock pen"],
    contact: "08671-256 300",
    updatedAt: ago(15),
  },
  {
    id: "SHL-27",
    name: "Municipal School, Avanigadda",
    district: "Krishna",
    location: { lat: 16.0221, lng: 80.9174 },
    capacity: 300,
    occupancy: 141,
    status: "OPEN",
    facilities: ["Kitchen", "Toilets"],
    contact: "08671-232 118",
    updatedAt: ago(55),
  },
  {
    id: "SHL-31",
    name: "Zilla Parishad Hall, Kollipara",
    district: "Guntur",
    location: { lat: 16.3357, lng: 80.7712 },
    capacity: 220,
    occupancy: 88,
    status: "OPEN",
    facilities: ["Drinking water", "Medical desk"],
    contact: "0863-229 7710",
    updatedAt: ago(33),
  },
];

export const hospitals: Hospital[] = [
  { id: "HOS-1", name: "Government General Hospital, Amalapuram", district: "Konaseema", location: { lat: 16.5721, lng: 82.0119 }, bedsAvailable: 46, ambulances: 6 },
  { id: "HOS-2", name: "Area Hospital, Kaikaluru", district: "Eluru", location: { lat: 16.5563, lng: 81.2118 }, bedsAvailable: 18, ambulances: 3 },
  { id: "HOS-3", name: "Government General Hospital, Guntur", district: "Guntur", location: { lat: 16.3062, lng: 80.4365 }, bedsAvailable: 132, ambulances: 14 },
  { id: "HOS-4", name: "Community Health Centre, Avanigadda", district: "Krishna", location: { lat: 16.0182, lng: 80.9223 }, bedsAvailable: 12, ambulances: 2 },
  { id: "HOS-5", name: "District Hospital, Machilipatnam", district: "Krishna", location: { lat: 16.1799, lng: 81.1385 }, bedsAvailable: 61, ambulances: 8 },
];

export const teams: ResponseTeam[] = [
  { id: "TEAM-BOAT-B", name: "Boat Rescue Team B", type: "BOAT_RESCUE", status: "AVAILABLE", members: 8, district: "Konaseema", location: { lat: 16.5402, lng: 81.8836 } },
  { id: "TEAM-BOAT-C", name: "Boat Rescue Team C", type: "BOAT_RESCUE", status: "DEPLOYED", members: 7, district: "Konaseema", location: { lat: 16.6109, lng: 82.0402 }, assignedIncidentId: "INC-24817" },
  { id: "TEAM-AMB-A7", name: "Ambulance A7 (108)", type: "MEDICAL", status: "EN_ROUTE", members: 3, district: "Konaseema", location: { lat: 16.6291, lng: 82.0723 }, assignedIncidentId: "INC-24822" },
  { id: "TEAM-NDRF-2", name: "NDRF Platoon 2", type: "NDRF", status: "DEPLOYED", members: 32, district: "Eluru", location: { lat: 16.5488, lng: 81.2265 } },
  { id: "TEAM-ENG-3", name: "R&B Engineering Unit 3", type: "ENGINEERING", status: "DEPLOYED", members: 11, district: "Eluru", location: { lat: 16.5601, lng: 81.2011 }, assignedIncidentId: "INC-24830" },
  { id: "TEAM-REL-9", name: "Relief Convoy 9", type: "RELIEF_DISTRIBUTION", status: "EN_ROUTE", members: 14, district: "Bapatla", location: { lat: 16.0902, lng: 80.7605 }, assignedIncidentId: "INC-24845" },
  { id: "TEAM-MED-4", name: "Mobile Medical Unit 4", type: "MEDICAL", status: "AVAILABLE", members: 6, district: "Krishna", location: { lat: 16.0231, lng: 80.9138 } },
  { id: "TEAM-BOAT-F", name: "Boat Rescue Team F", type: "BOAT_RESCUE", status: "RESTING", members: 8, district: "Guntur", location: { lat: 16.3288, lng: 80.7801 } },
];

export const resources: ResourceItem[] = [
  { id: "RES-01", name: "Dry ration kits", unit: "kits", category: "FOOD", stock: 4820, allocated: 3100, reorderLevel: 2000, warehouse: "Guntur Central Godown" },
  { id: "RES-02", name: "Drinking water pouches", unit: "cartons", category: "WATER", stock: 1240, allocated: 980, reorderLevel: 1500, warehouse: "Eluru Godown" },
  { id: "RES-03", name: "ORS sachets", unit: "boxes", category: "MEDICAL", stock: 760, allocated: 420, reorderLevel: 300, warehouse: "Amalapuram Medical Store" },
  { id: "RES-04", name: "Tarpaulin sheets", unit: "sheets", category: "SHELTER_KIT", stock: 2100, allocated: 1450, reorderLevel: 800, warehouse: "Machilipatnam Godown" },
  { id: "RES-05", name: "Inflatable rescue boats", unit: "units", category: "EQUIPMENT", stock: 22, allocated: 17, reorderLevel: 10, warehouse: "SDRF Base, Vijayawada" },
  { id: "RES-06", name: "Emergency medicine kits", unit: "kits", category: "MEDICAL", stock: 310, allocated: 288, reorderLevel: 200, warehouse: "Amalapuram Medical Store" },
  { id: "RES-07", name: "Portable generators", unit: "units", category: "EQUIPMENT", stock: 48, allocated: 31, reorderLevel: 20, warehouse: "Guntur Central Godown" },
];

export const alerts: Alert[] = [
  {
    id: "ALT-901",
    headline: "Red alert: Godavari at Dowleswaram above second warning level",
    body: "Inflow of 14.6 lakh cusecs recorded. Lanka villages in Konaseema advised to evacuate to designated shelters immediately.",
    severity: "CRITICAL",
    districts: ["Konaseema", "Kakinada"],
    issuedAt: ago(45),
    source: "AP State Disaster Management Authority",
  },
  {
    id: "ALT-902",
    headline: "Orange alert: Heavy to very heavy rainfall for coastal districts",
    body: "IMD Amaravati forecasts 12-20 cm rainfall in the next 24 hours across Krishna, Guntur, Bapatla and Eluru.",
    severity: "HIGH",
    districts: ["Krishna", "Guntur", "Bapatla", "Eluru"],
    issuedAt: ago(150),
    source: "IMD Amaravati",
  },
  {
    id: "ALT-903",
    headline: "Fishermen advised not to venture into the sea",
    body: "Squally weather with wind speeds up to 55 kmph likely along and off the AP coast until tomorrow evening.",
    severity: "MEDIUM",
    districts: ["Bapatla", "Nellore", "Prakasam"],
    issuedAt: ago(320),
    source: "Cyclone Warning Centre, Visakhapatnam",
  },
  {
    id: "ALT-904",
    headline: "Kolleru link bridge closed to heavy vehicles",
    body: "Approach slab damage confirmed. Divert via NH-216. Restoration under way.",
    severity: "HIGH",
    districts: ["Eluru"],
    issuedAt: ago(200),
    source: "Roads & Buildings Department",
  },
];

export const riskZones: RiskZone[] = [
  {
    id: "RZ-1",
    name: "Konaseema lanka villages inundation belt",
    level: "CRITICAL",
    district: "Konaseema",
    note: "Godavari spill zone; historic inundation in 2022 and 2024 events.",
    polygon: [
      { lat: 16.72, lng: 81.86 },
      { lat: 16.74, lng: 82.13 },
      { lat: 16.5, lng: 82.18 },
      { lat: 16.44, lng: 81.9 },
    ],
  },
  {
    id: "RZ-2",
    name: "Kolleru lake fringe",
    level: "HIGH",
    district: "Eluru",
    note: "Backwater rise expected with sustained upstream rainfall.",
    polygon: [
      { lat: 16.66, lng: 81.12 },
      { lat: 16.66, lng: 81.36 },
      { lat: 16.46, lng: 81.36 },
      { lat: 16.45, lng: 81.13 },
    ],
  },
  {
    id: "RZ-3",
    name: "Krishna delta low-lying belt",
    level: "HIGH",
    district: "Krishna",
    note: "Diviseema mandals; tidal ingress compounds river spill.",
    polygon: [
      { lat: 16.12, lng: 80.82 },
      { lat: 16.14, lng: 81.05 },
      { lat: 15.9, lng: 81.02 },
      { lat: 15.88, lng: 80.83 },
    ],
  },
  {
    id: "RZ-4",
    name: "Bapatla coastal surge zone",
    level: "MEDIUM",
    district: "Bapatla",
    note: "Storm-surge exposure within 3 km of coastline.",
    polygon: [
      { lat: 16.05, lng: 80.72 },
      { lat: 16.02, lng: 80.95 },
      { lat: 15.86, lng: 80.9 },
      { lat: 15.9, lng: 80.7 },
    ],
  },
];

export const roads: RoadSegment[] = [
  {
    id: "RD-1",
    name: "Kolleru link road (Kaikaluru approach)",
    status: "BLOCKED",
    reason: "Bridge approach slab washed out",
    path: [
      { lat: 16.5652, lng: 81.1902 },
      { lat: 16.5581, lng: 81.2094 },
      { lat: 16.5502, lng: 81.2287 },
    ],
  },
  {
    id: "RD-2",
    name: "Amalapuram – Mummidivaram road",
    status: "RESTRICTED",
    reason: "Water over carriageway, light vehicles only",
    path: [
      { lat: 16.5786, lng: 82.0061 },
      { lat: 16.6102, lng: 82.049 },
      { lat: 16.6407, lng: 82.0894 },
    ],
  },
  {
    id: "RD-3",
    name: "NH-216 Machilipatnam bypass",
    status: "OPEN",
    reason: "Designated diversion route",
    path: [
      { lat: 16.1875, lng: 81.1389 },
      { lat: 16.1, lng: 81.05 },
      { lat: 16.02, lng: 80.93 },
    ],
  },
  {
    id: "RD-4",
    name: "Repalle – Kollipara relief corridor",
    status: "OPEN",
    reason: "Relief convoy corridor",
    path: [
      { lat: 16.0189, lng: 80.8291 },
      { lat: 16.18, lng: 80.79 },
      { lat: 16.3389, lng: 80.7645 },
    ],
  },
];

export const infrastructure: InfrastructureAsset[] = [
  { id: "INF-1", name: "Kolleru link bridge", type: "BRIDGE", district: "Eluru", location: { lat: 16.5581, lng: 81.2094 }, condition: "DAMAGED", lastInspected: ago(120) },
  { id: "INF-2", name: "Nagayalanka DTR substation", type: "SUBSTATION", district: "Krishna", location: { lat: 15.9541, lng: 80.9209 }, condition: "AT_RISK", lastInspected: ago(300) },
  { id: "INF-3", name: "Ainavilli embankment reach 4", type: "EMBANKMENT", district: "Konaseema", location: { lat: 16.5488, lng: 81.8951 }, condition: "MONITORED", lastInspected: ago(60) },
  { id: "INF-4", name: "Repalle water treatment plant", type: "WATER_TREATMENT", district: "Bapatla", location: { lat: 16.0231, lng: 80.8404 }, condition: "STABLE", lastInspected: ago(720) },
  { id: "INF-5", name: "Kaikaluru pump house 2", type: "PUMP_HOUSE", district: "Eluru", location: { lat: 16.5471, lng: 81.2352 }, condition: "AT_RISK", lastInspected: ago(180) },
];

export const volunteerTasks: VolunteerTask[] = [
  {
    id: "TSK-501",
    title: "Assist boat evacuation at Chinthalapalem",
    incidentId: "INC-24817",
    district: "Konaseema",
    location: { lat: 16.5561, lng: 81.9012 },
    priority: "CRITICAL",
    status: "OFFERED",
    instructions: "Report to Boat Team B staging point. Carry life jacket. Assist elderly and infants boarding only under team lead instruction.",
    dueBy: ago(-60),
  },
  {
    id: "TSK-506",
    title: "Distribute 120 dry ration kits at SHL-18",
    incidentId: "INC-24845",
    district: "Bapatla",
    location: { lat: 16.0176, lng: 80.8302 },
    priority: "HIGH",
    status: "ACCEPTED",
    instructions: "Collect kits from Relief Convoy 9. Record household token numbers in the camp register.",
    dueBy: ago(-180),
  },
  {
    id: "TSK-509",
    title: "Verify water quality complaint at Kaikaluru camp",
    incidentId: "INC-24834",
    district: "Eluru",
    location: { lat: 16.5502, lng: 81.2201 },
    priority: "HIGH",
    status: "IN_PROGRESS",
    instructions: "Collect two water samples, photograph the borewell head and submit a field update.",
    dueBy: ago(-45),
  },
  {
    id: "TSK-512",
    title: "Shelter roof repair support at Avanigadda",
    incidentId: "INC-24861",
    district: "Krishna",
    location: { lat: 16.0203, lng: 80.9192 },
    priority: "MEDIUM",
    status: "COMPLETED",
    instructions: "Assist R&B team with tarpaulin fixing over classroom block B.",
    dueBy: ago(120),
  },
];

export const fieldUpdates: FieldUpdate[] = [
  { id: "FU-77", submittedBy: "Volunteer Harika P.", role: "VOLUNTEER", district: "Krishna", kind: "SHELTER_CONDITION", note: "Classroom block B roof still leaking after first repair attempt; 60 evacuees in corridor.", reviewState: "PENDING_REVIEW", submittedAt: ago(38), hasEvidence: true },
  { id: "FU-78", submittedBy: "Volunteer Team Sankalp", role: "VOLUNTEER", district: "Eluru", kind: "RESOURCE_NEED", note: "Camp requires 200 water cartons within 12 hours.", reviewState: "PENDING_REVIEW", submittedAt: ago(52), hasEvidence: false },
  { id: "FU-79", submittedBy: "Dr. Prasad Yalamanchili", role: "VOLUNTEER", district: "Konaseema", kind: "OBSERVATION", note: "Two more households on the same lane report elderly patients needing medicines.", reviewState: "VERIFIED", submittedAt: ago(96), hasEvidence: true },
  { id: "FU-80", submittedBy: "Volunteer Naveen K.", role: "VOLUNTEER", district: "Eluru", kind: "ROAD_CONDITION", note: "Water receded on Kaikaluru bypass; light vehicles passable.", reviewState: "VERIFIED", submittedAt: ago(150), hasEvidence: true },
  { id: "FU-81", submittedBy: "Volunteer Imran S.", role: "VOLUNTEER", district: "Guntur", kind: "OBSERVATION", note: "Reported breach near canal bund — later found to be routine sluice release.", reviewState: "REJECTED", submittedAt: ago(400), hasEvidence: false },
];

export const donationNeeds: DonationNeed[] = [
  { id: "NEED-01", title: "Drinking water for Eluru relief camps", district: "Eluru", category: "WATER", requiredUnits: 1800, pledgedUnits: 1100, receivedUnits: 640, urgency: "CRITICAL", verifiedBy: "District Collector, Eluru" },
  { id: "NEED-02", title: "Dry ration kits for Konaseema lanka villages", district: "Konaseema", category: "FOOD", requiredUnits: 3000, pledgedUnits: 2250, receivedUnits: 1980, urgency: "HIGH", verifiedBy: "Revenue Divisional Officer, Amalapuram" },
  { id: "NEED-03", title: "Emergency medicine kits", district: "Krishna", category: "MEDICAL", requiredUnits: 400, pledgedUnits: 180, receivedUnits: 150, urgency: "HIGH", verifiedBy: "District Medical & Health Officer" },
  { id: "NEED-04", title: "Tarpaulin sheets for temporary shelters", district: "Bapatla", category: "SHELTER_KIT", requiredUnits: 1200, pledgedUnits: 900, receivedUnits: 900, urgency: "MEDIUM", verifiedBy: "District Collector, Bapatla" },
];

export const contributions: Contribution[] = [
  { id: "CON-330", donor: "Sagar Infra Foundation", kind: "IN_KIND", description: "Drinking water pouches", units: 640, state: "DISTRIBUTED", createdAt: ago(900), needId: "NEED-01" },
  { id: "CON-341", donor: "Sagar Infra Foundation", kind: "IN_KIND", description: "Drinking water pouches", units: 460, state: "IN_TRANSIT", createdAt: ago(180), needId: "NEED-01" },
  { id: "CON-352", donor: "Sagar Infra Foundation", kind: "FINANCIAL", description: "Contribution to CM Relief Fund (disaster head)", amount: 500000, state: "RECEIVED", createdAt: ago(1400) },
  { id: "CON-361", donor: "Sagar Infra Foundation", kind: "IN_KIND", description: "Emergency medicine kits", units: 150, state: "RECEIVED", createdAt: ago(520), needId: "NEED-03" },
  { id: "CON-370", donor: "Sagar Infra Foundation", kind: "IN_KIND", description: "Tarpaulin sheets", units: 300, state: "PLEDGED", createdAt: ago(60), needId: "NEED-04" },
];

export const weather: WeatherSnapshot[] = [
  { district: "Konaseema", condition: "Heavy rain", rainfall24hMm: 168, windKph: 41, riverLevelM: 14.9, riverDangerM: 13.75, advisory: "CRITICAL" },
  { district: "Eluru", condition: "Heavy rain", rainfall24hMm: 121, windKph: 33, riverLevelM: 9.4, riverDangerM: 10.2, advisory: "HIGH" },
  { district: "Krishna", condition: "Moderate rain", rainfall24hMm: 88, windKph: 29, riverLevelM: 11.2, riverDangerM: 12.5, advisory: "HIGH" },
  { district: "Guntur", condition: "Moderate rain", rainfall24hMm: 74, windKph: 26, riverLevelM: 10.8, riverDangerM: 12.5, advisory: "MEDIUM" },
  { district: "Bapatla", condition: "Squally winds", rainfall24hMm: 52, windKph: 55, riverLevelM: 6.1, riverDangerM: 8.0, advisory: "MEDIUM" },
];

export const auditLog: AuditEntry[] = [
  { id: "AUD-9001", at: ago(12), actor: "Control Room", role: "ADMIN", action: "Dispatched Ambulance A7", target: "INC-24822" },
  { id: "AUD-9002", at: ago(21), actor: "Officer R. Vamsi Krishna", role: "FIELD_OFFICER", action: "Verified incident and raised severity to CRITICAL", target: "INC-24817" },
  { id: "AUD-9003", at: ago(52), actor: "Officer K. Anitha", role: "FIELD_OFFICER", action: "Marked INC-24841 as possible duplicate of INC-24839", target: "INC-24841" },
  { id: "AUD-9004", at: ago(88), actor: "Control Room", role: "ADMIN", action: "Released 1,200 dry ration kits to Relief Convoy 9", target: "RES-01" },
  { id: "AUD-9005", at: ago(150), actor: "System", role: "ADMIN", action: "Published orange alert for coastal districts", target: "ALT-902" },
  { id: "AUD-9006", at: ago(240), actor: "Officer K. Anitha", role: "FIELD_OFFICER", action: "Approved shelter capacity revision", target: "SHL-18" },
];

export const platformUsers: PlatformUser[] = [
  { id: "USR-1", name: "Sailaja Kondapalli", role: "CITIZEN", district: "Konaseema", status: "ACTIVE", joinedAt: ago(60000) },
  { id: "USR-2", name: "Dr. Prasad Yalamanchili", role: "VOLUNTEER", district: "Konaseema", status: "ACTIVE", joinedAt: ago(90000) },
  { id: "USR-3", name: "Volunteer Harika P.", role: "VOLUNTEER", district: "Krishna", status: "ACTIVE", joinedAt: ago(43000) },
  { id: "USR-4", name: "Officer R. Vamsi Krishna", role: "FIELD_OFFICER", district: "Eluru", status: "ACTIVE", joinedAt: ago(120000) },
  { id: "USR-5", name: "Officer K. Anitha", role: "FIELD_OFFICER", district: "Guntur", status: "ACTIVE", joinedAt: ago(150000) },
  { id: "USR-6", name: "Sagar Infra Foundation", role: "DONOR", district: "NTR", status: "ACTIVE", joinedAt: ago(200000), organisation: "Sagar Infra Foundation" },
  { id: "USR-7", name: "Kavya Reddy", role: "VOLUNTEER", district: "Bapatla", status: "PENDING_VERIFICATION", joinedAt: ago(900) },
  { id: "USR-8", name: "Coastal Relief Trust", role: "DONOR", district: "Krishna", status: "PENDING_VERIFICATION", joinedAt: ago(2400), organisation: "Coastal Relief Trust" },
];

export const emergencyContacts = [
  { label: "State Emergency Operations Centre", number: "1070", note: "24x7 disaster helpline" },
  { label: "District Emergency Operations Centre", number: "1077", note: "District control room" },
  { label: "Ambulance", number: "108", note: "Medical emergency" },
  { label: "Police", number: "100", note: "Law and order" },
  { label: "Fire & Rescue", number: "101", note: "Fire and rescue services" },
  { label: "Women Helpline", number: "181", note: "Women in distress" },
  { label: "Childline", number: "1098", note: "Children in distress" },
];

export const incidentTrend = [
  { hour: "00:00", reports: 18, verified: 11 },
  { hour: "03:00", reports: 26, verified: 17 },
  { hour: "06:00", reports: 41, verified: 28 },
  { hour: "09:00", reports: 63, verified: 44 },
  { hour: "12:00", reports: 88, verified: 61 },
  { hour: "15:00", reports: 112, verified: 79 },
  { hour: "18:00", reports: 128, verified: 96 },
];

export const responseTimeTrend = [
  { day: "Mon", minutes: 41 },
  { day: "Tue", minutes: 38 },
  { day: "Wed", minutes: 46 },
  { day: "Thu", minutes: 33 },
  { day: "Fri", minutes: 29 },
  { day: "Sat", minutes: 31 },
  { day: "Sun", minutes: 27 },
];

export const situationSummary = {
  activeIncidents: 128,
  criticalIncidents: 12,
  openShelters: 84,
  responseTeams: 42,
  peopleAssisted: 21460,
  resourcesDeployed: 9840,
  verifiedIncidents: 96,
  resolutionRate: 78,
};
